### ISSUE TITLE
Travis jobs using content_shell fail because of missing Arial font

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1080]
It would seem that the `content_shell` requires the Arial font which isn't installed by default on the Travis VMs we use. Instead we manually install Arial (and other needed fonts) using `ttf-mscorefonts-installer`. The installer attempts to get the fonts from Sourceforge (e.g. http://downloads.sourceforge.net/corefonts/andale32.exe) and under heavy loads, this attempt sometimes fails:

```nocode
ttf-mscorefonts-installer: downloading http://downloads.sourceforge.net/corefonts/andale32.exe
Traceback (most recent call last):
  File "/usr/lib/update-notifier/package-data-downloader", line 239, in process_download_requests
    dest_file = urllib.urlretrieve(files[i])[0]
  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 359, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 372, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 635, in http_error_302
    data)
  File "/usr/lib/python2.7/urllib.py", line 661, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 437, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

We need to find an alternative that works more consistently.

**Comment by chalin** [comment]
Finally found a fix: adapted from [SO](https://stackoverflow.com/a/37887105/3046255); original fix suggested by @zoechi in https://github.com/dart-lang/test/issues/415#issuecomment-202776591 (thanks!).
