### ISSUE TITLE
[master] examples/ng/doc/toh-6

### ISSUE THREAD

**Issue by CrazyStaff** [dart-lang/site-webdev#1664]
i get the following issue on webdev serve

```nocode
C:\Users\Johan\Desktop\toh-6-master\toh-6-master>webdev serve
Crash when formatting: [Encoding] Unable to decode bytes as UTF-8.
RangeError (index): Invalid value: Not in range 0..271105, inclusive: 271467
#0      _StringBase.[] (dart:core/runtime/libstring_patch.dart:233:55)
#1      Source.getTextLine (package:kernel/ast.dart:5772:42)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:27:9)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:80:27)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:206:32)
#5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:215:22)
#6      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:67:13)
#7      Loader.addMessage (package:front_end/src/fasta/loader.dart:258:20)
#8      Loader.addCompileTimeError (package:front_end/src/fasta/loader.dart:207:5)
#9      LibraryBuilder.addCompileTimeError 
...
```

**Comment by chalin** [comment]
Hi Johannes. Which version of the SDK are you using? Maybe you are hitting [this problem](https://github.com/dart-lang/stagehand/issues/543#issuecomment-399668142)? If so, instead run:

```console
> pub global run webdev serve
```

**Comment by CrazyStaff** [comment]
Hey Patrice. Thank you this works !! :)
