### ISSUE TITLE
pub upgrade fails for template-syntax

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1834]
Due to transitive package [dependency incompatibilities with pageloader](https://github.com/google/pageloader/issues/158#issuecomment-432419824), the template-syntax example can't be built:

```nocode
Because code_builder >=0.1.3 <3.1.2 requires SDK version >=1.9.1 <2.0.0-∞ and code_builder >=3.1.2 <3.1.3 depends on built_collection >=1.0.0 <4.0.0, code_builder >=0.1.3 <3.1.3 requires built_collection >=1.0.0 <4.0.0.
And because code_builder >=3.1.3 depends on built_value ^6.0.0, code_builder >=0.1.3 requires built_value ^6.0.0 or built_collection >=1.0.0 <4.0.0.
And because angular >=5.0.0-beta+1 depends on code_builder ^3.0.1 and pageloader >=3.0.0-beta depends on built_value ^5.1.0, if pageloader >=3.0.0-beta and angular >=5.0.0-beta+1 then built_collection >=1.0.0 <4.0.0.
And because template_syntax depends on angular_components ^0.10.0 which depends on built_collection ^4.0.0, pageloader >=3.0.0-beta is incompatible with angular >=5.0.0-beta+1.
So, because template_syntax depends on both angular ^5.0.0 and pageloader ^3.0.1, version solving failed.
```

**Comment by kwalrath** [comment]
I'm still getting this, despite their fix:

```
Because pageloader >=3.0.2 depends on analyzer ^0.32.5 and angular >=5.1.0 depends on analyzer ^0.33.0, pageloader >=3.0.2 is incompatible with angular >=5.1.0.
So, because template_syntax depends on both angular ^5.1.0 and pageloader ^3.0.2, version solving failed.
```

**Comment by chalin** [comment]
This is what I'm getting now (for NG 5.1.0):

```nocode
Because pageloader >=3.0.2 depends on analyzer ^0.32.5 and no versions of pageloader match >3.0.1 <3.0.2, pageloader >3.0.1 requires analyzer ^0.32.5.
And because pageloader 3.0.1 depends on built_value ^5.1.0 and code_builder >=3.1.3 depends on built_value ^6.0.0, if pageloader >=3.0.1 and code_builder >=3.1.3 then analyzer ^0.32.5.
Because no versions of code_builder match >3.1.2 <3.1.3 and code_builder >=0.1.3 <3.1.2 requires SDK version >=1.9.1 <2.0.0-∞, code_builder >=0.1.3 <3.1.2-∞ or >3.1.2 <3.1.3-∞ is forbidden.
Thus, if pageloader >=3.0.1 and code_builder >=0.1.3 <3.1.2-∞ or >3.1.2 then analyzer ^0.32.5.
And because angular >=5.0.0-beta+1 depends on code_builder ^3.0.1, if pageloader >=3.0.1 and angular >=5.0.0-beta+1 then analyzer ^0.32.5 or code_builder 3.1.2.

Because angular >=5.2.0 depends on analyzer ^0.34.0 and angular >=5.1.0 <5.2.0 depends on analyzer ^0.33.0, angular >=5.1.0 requires analyzer ^0.33.0 or ^0.34.0.
Thus, if angular >=5.1.0 and pageloader >=3.0.1 then code_builder 3.1.2.

And because angular_components >=0.10.0 depends on angular ^5.1.0, if pageloader >=3.0.1 and angular_components >=0.10.0 then code_builder 3.1.2.

And because code_builder 3.1.2 depends on built_collection >=1.0.0 <4.0.0 and angular_components >=0.9.2 depends on built_collection ^4.0.0, pageloader >=3.0.1 is incompatible with angular_components >=0.10.0.
So, because template_syntax depends on both angular_components ^0.10.0 and pageloader ^3.0.1, version solving failed.
```

I've opened https://github.com/google/pageloader/issues/169. There also seems to be an (indirect) issue with the `built_collection` version constraints, but let's upgrade to NG 5.2.0 first before analyzing this situation further.

**Comment by chalin** [comment]
Great that the app is building now!

@kwalrath, you should also reenable E2E and component tests (see the FIXME comments below) for the template app:
https://github.com/dart-lang/site-webdev/blob/160be734dc3b0361a2e87b295eed8f00540f37a3/.travis.yml#L60-L66

**Comment by kwalrath** [comment]
From https://travis-ci.org/dart-lang/site-webdev/jobs/470637795:

```
E2E for examples/ng/doc/template-syntax
EXEC start: npm run http-server -- /home/travis/build/dart-lang/site-webdev/examples/ng/doc/template-syntax/build/web -s {"cwd":"examples/ng/doc/template-syntax"}
EXEC start: pub get {"cwd":"examples/ng/doc/template-syntax"}
EXEC DONE: command return code is nonzero value null - npm run http-server -- /home/travis/build/dart-lang/site-webdev/examples/ng/doc/structural-directives/build/web -s {"cwd":"examples/ng/doc/structural-directives"}

> angular-examples-master@1.0.0 http-server /home/travis/build/dart-lang/site-webdev/examples/ng/doc
> http-server "/home/travis/build/dart-lang/site-webdev/examples/ng/doc/template-syntax/build/web" "-s"
EXEC DONE: successfully exited from pub get # examples/ng/doc/template-syntax
EXEC start: pub global run webdev build --no-release --output=build {"cwd":"examples/ng/doc/template-syntax","okOnExitRE":{},"errorOnExitRE":{}}

...

EXEC DONE: match for /\[SEVERE\]|\[WARNING\](?! (\w+: )?(Invalidating asset graph|Throwing away cached asset graph|No actions completed for ))/ found in stdout or stderr of pub global run webdev build --no-release --output=build # examples/ng/doc/template-syntax
runExampleE2E over examples/ng/doc/template-syntax failed.
[10:39:17] 'e2e' errored after 11 min
[10:39:17] Error: match for /\[SEVERE\]|\[WARNING\](?! (\w+: )?(Invalidating asset graph|Throwing away cached asset graph|No actions completed for ))/ found in stdout or stderr of pub global run webdev build --no-release --output=build # examples/ng/doc/template-syntax
    at formatError (/home/travis/build/dart-lang/site-webdev/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:20:10)
    at Gulp.<anonymous> (/home/travis/build/dart-lang/site-webdev/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:31:15)
    at Gulp.emit (events.js:187:15)
    at Gulp.EventEmitter.emit (domain.js:441:20)
    at Object.error (/home/travis/build/dart-lang/site-webdev/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/home/travis/build/dart-lang/site-webdev/node_modules/now-and-later/lib/map.js:46:14)
    at f (/home/travis/build/dart-lang/site-webdev/node_modules/once/once.js:25:25)
    at f (/home/travis/build/dart-lang/site-webdev/node_modules/once/once.js:25:25)
    at tryCatch (/home/travis/build/dart-lang/site-webdev/node_modules/async-done/index.js:24:15)
    at done (/home/travis/build/dart-lang/site-webdev/node_modules/async-done/index.js:40:12)
travis_time:end:124054f0:start=1545330503578656701,finish=1545331157593609252,duration=654014952551
The command "npx gulp $TASK" exited with 1.
...
```
